### ISSUE TITLE
the optimal value and solution don't seem right

### ISSUE THREAD

**Issue by studymeow** [goulart-paul/osqp-r#22]
I am trying to solve quadratic programming in R with package osqp. However, the result doesn't look right to me. I really appreciate your suggestion.

The code for reproducing the example attached here:（the objective function is the minimization

```
library(osqp)
library(Matrix)
P <- Matrix(c(1., 0.,0,
              0., 1.,0, 0,0,1), 3, 3, sparse = TRUE)
q <- c(0, 1,1)
A <- Matrix(c(1., 1., 0.,
              1., 0., 1.,1,0,1), 3, 3, sparse = TRUE)
l <- c(1.2, 0., 0.7)
u <- c(2., 0.8, 0.7)
settings <- osqpSettings(alpha = 1.0,eps_abs = 1.0e-05, eps_rel = 1.0e-05,)
model <- osqp(P, q, A, l, u, settings)
res <- model$Solve()

```

This is the output of the model, and it shows the optimal value is 0.7

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Is9Wi.png

However, if use the optimal solution to plug into the objective function it gives me 1.018556

```
#this should be the final objective value after solving
0.5*t(res$x)%*%P%*%res$x+t(c(0,1,1))%*%res$x

#the solution
res$x
#0.6261887 0.3500000 0.3500000

```

More importantly, i think this is not the optimal solution. If I eyeballed the solution, I could find another answer with a smaller objective function with a value of 0.5,0.1,0.6
I am not sure what I did wrong. 

Thank you for any advice in advance!

**Comment by goulart-paul** [comment]
The issue appears to be that OSQP is not properly receiving the `P` matrix.    When I run your example code above, OSQP reports that `nnz(A) + nnz(P) = 6`, which is obviously not correct since `A` itself has 6 nonzeros.  I think it has simply ignored `P` for some reason.

If I replace your `P` with 
``
P <- Matrix(c(1, 0,0,
              1e-10, 1,0, 0,0,1), 3, 3, sparse = TRUE)
``
and rerun, then I get `nnz(P) + nnz(A) = 10`, which is correct (counting only the upper triangle of `P`).  I also get the solution `[0.5 0.35 0.35]`, which also appears to be correct and matches the solution obtained from OSQP through our other language interfaces.

The underlying issue appears to be a failure to properly process `P` because it is of type `ddiMatrix` in your example, and OSQP only seems to understand it if it is of type `dsCMatrix`.    For example, this seems to work:
```
model <- osqp(forceSymmetric(P), q, A, l, u, settings)
res <- model$Solve()
```
As does this:
```
P <- as(as(P,"symmetricMatrix"),"dsCMatrix")
```

The user should not have to do that though.   I'm not very familiar with R, so I will leave this open for now and come back to it as time permits, unless someone else can propose a fix.
