### ISSUE TITLE
Time_limit in osqpSettings

### ISSUE THREAD

**Issue by tomasruizt** [goulart-paul/osqp-r#23]
Hi!
I'm unable to set the `time_limit` parameter:
```R
> osqp::osqpSettings(time_limit = 10)
Error in osqp::osqpSettings(time_limit = 10) : 
  unused argument (time_limit = 10)
```
I'm using the most up-to-date version of the interface
```R
> packageVersion("osqp")
[1] ‘0.6.0.3’
```
Am I doing something wrong?
Cordially,

**Comment by goulart-paul** [comment]
I don't think you are doing anything wrong.   As far as I can tell, support for this parameter appears not to have been implemented through the R interface.   I don't really understand why, since it is in the changelog for v0.3.0, which is by now quite old.

You could achieve a similar effect using `max_iter`, but I would agree that that is not ideal.   I will leave this issue open and we will try to fix it in the next update.

**Comment by tomasruizt** [comment]
Thank you that is very kind! We are already using `max_iter,` but really we are looking for the `time_limit` option. If it helps and you are short on time, I can contribute a PR with the change. I'd need some basic guidance on the codebase, though.
Best,

**Comment by goulart-paul** [comment]
Maybe give this a whirl?:
https://github.com/oxfordcontrol/osqp-r/tree/pg/time_limit_fix

**Comment by tomasruizt** [comment]
Looks great, I'm able to get the correct status -6 using R after passing `time_limit`:
```
status:               run time limit reached
number of iterations: 4723
run time:             1.00e-01s
optimal rho estimate: 6.28e+03
```

**Comment by goulart-paul** [comment]
OK.  I have made a PR for this fix and we will aim to get it into the next release.
