### ISSUE TITLE
R-package is going to be archived

### ISSUE THREAD

**Issue by FlorianSchwendinger** [goulart-paul/osqp-r#26]
My **R** package imports package [osqp](https://cran.r-project.org/web/packages/osqp/index.html), I got an E-Mail from Prof Brian Ripley that your package will be archived due to the following reason:

``We have asked for an update fixing the check problems shown at
  <https://cran.r-project.org/web/checks/check_results_osqp.html>
with no update from the maintainer thus far.''

Are you aware of this (since university e-mail adresses can change)? 
If this is not on purpose please get in contact with CRAN@R-project.org .

I will write back that I created an issue here.

**Comment by lrnv** [comment]
My package also depends on OSQP, and a few others too. We hope this will get fixed !

**Comment by goulart-paul** [comment]
We are aware of the problem and will try to make a fix.    Any help is appreciated because none of our core developer team are really R users.   In summary, the problem is that the OSQP build fails when trying to compile with a development version of R on an M1 mac machine.   All of the tests on CRAN pass (see [here](https://cran.r-project.org/web/checks/check_results_osqp.html)) except for the one with the link at the very bottom outside the table.   

The failed test log is [here](https://www.stats.ox.ac.uk/pub/bdr/M1mac/osqp.log).    The problem comes from within cmake, at [this line](https://github.com/osqp/osqp/blob/33454b3e236f1f44193bfbbb6b8c8e71f8f04e9a/CMakeLists.txt#L243), wherein we call `find_package(R)`.   That fails for some reason, presumably because the R install on the test machine is somehow non-standard or non-recognized by cmake.   I believe that they are running there with a development version of R and with the main R executable named `Rdev` rather than just `R`.

A fix might be as easy as finding some other package on CRAN that uses a cmake based build, because it seems hard to believe that we are the only ones.

**Comment by goulart-paul** [comment]
I guess that the problem is that `Rdev` is not listed as an option to search for in the cmake R config file [this line](https://github.com/osqp/osqp/blob/33454b3e236f1f44193bfbbb6b8c8e71f8f04e9a/configure/cmake/FindR.cmake#L11).  

Possibly just adding `Rdev` there would solve the problem.   I don't have a dev install of R to test it on though.   Anyone?

I also have no idea where that FindR.cmake file came from.   Perhaps there is some more robust version available, but note that the current version includes some weirdness to work around an issue that arose because CRAN insists that everything should compile on solaris.   I have no memory of fixing that but it must have been me.

**Comment by danigiro** [comment]
> We are aware of the problem and will try to make a fix.    Any help is appreciated because none of our core developer team are really R users.   In summary, the problem is that the OSQP build fails when trying to compile with a development version of R on an M1 mac machine.   All of the tests on CRAN pass (see [here](https://cran.r-project.org/web/checks/check_results_osqp.html)) except for the one with the link at the very bottom outside the table.   
> 
> The failed test log is [here](https://www.stats.ox.ac.uk/pub/bdr/M1mac/osqp.log).    The problem comes from within cmake, at [this line](https://github.com/osqp/osqp/blob/33454b3e236f1f44193bfbbb6b8c8e71f8f04e9a/CMakeLists.txt#L243), wherein we call `find_package(R)`.   That fails for some reason, presumably because the R install on the test machine is somehow non-standard or non-recognized by cmake.   I believe that they are running there with a development version of R and with the main R executable named `Rdev` rather than just `R`.
> 
> A fix might be as easy as finding some other package on CRAN that uses a cmake based build, because it seems hard to believe that we are the only ones.
> 
> 
> 
> 

HI, also the package I maintain uses osqp. 

Unfortunately I'm not really a cmake expert, but I seem to have found that the lightgbm package also uses this system and doesn't experience this problem. I leave you the link to their cmake https://github.com/microsoft/LightGBM/blob/master/cmake/modules/FindLibR.cmake

I hope this can be helpful and not a waste of time.

Let us know as soon as you have any news. Thanks for your work.
Daniele

**Comment by FlorianSchwendinger** [comment]
I run a check with [**rhub**](https://builder.r-hub.io/) on the source code currently on CRAN on the platform
```
name             "macos-m1-bigsur-release"                          
description      "Apple Silicon (M1), macOS 11.6 Big Sur, R-release"
cran-name        "r-release-macos-arm64"                            
rversion         "r-release"                                        
os-type          "macOS"                                            
cpu-type         "aarch64"                                          
os-info          "Mac OS 11.6"                                      
compilers        "XCode 12.4, Apple clang version 12.0.0"           
docker-image     "NA"                                               
sysreqs-platform "osx-aarch64-clang"                                
categories       "macOS"                                            
node-labels      character,3                                        
queue            "m1"                                               
output-parser    "NA"                                               
macos-version    "bigsur"                                           
params           "NA"   
```

So should run on a M1 chip as well.

```r
library("rhub")

email <- ""
token <- ""
validate_email(email, token = token)

platform <- c("macos-m1-bigsur-release")
check_args <- "'--no-manual --no-build-vignettes'"
check("osqp-cran", platform = platform, email = email, check_args = check_args)
```

There it seems it worked, you find the html version of the results here.
[check-results](https://builder.r-hub.io/status/osqp_0.6.0.3.tar.gz-ca43191c4fa5475bb78796f28184b591)

**Comment by bnaras** [comment]
> I also have no idea where that FindR.cmake file came from. Perhaps there is some more robust version available, but note that the current version includes some weirdness to work around an issue that arose because CRAN insists that everything should compile on solaris. I have no memory of fixing that but it must have been me.

I see `FindR.cmake` [here](https://github.com/root-project/root/blob/master/cmake/modules/FindR.cmake) and if that is the one that is being used---a reasonable bet since that's a CERN repo---one sees that [line 21](https://github.com/root-project/root/blob/6cb78dcb67252d230024c7690f0590a6088e5803/cmake/modules/FindR.cmake#L21) looks for the executable `R` or `R.exe`.  But for checks against `R-devel`, that should be followed by a line to look for executables `R-devel` and `R-devel.exe` _if_ the first check fails.  (How do I know it should be `R-devel`? I get a hint from the first line of [this](https://www.stats.ox.ac.uk/pub/bdr/Rconfig/r-devel-linux-x86_64-fedora-clang), where `osqp` is also now failing, in addition to M1 arch.)

I too am no CMake expert, but if it is possible to include the module in the osqp sources, and cmake made to look for it locally using perhaps hints [here](https://stackoverflow.com/questions/51564251/correct-way-to-use-third-party-libraries-in-cmake-project),  a fix may be possible.

**Comment by FlorianSchwendinger** [comment]
For me the following did work at Debian.
1. Delete `osqp/configure/cmake/FindR.cmake`
2. In `osqp/CMakeLists.txt` comment out line 234 (`    # find_package(R)`).
3. change the configure to something like this
https://github.com/FlorianSchwendinger/osqp-r/blob/master/configure

The basic idea don't search for **R**, let **R** tell you where it lives. I assume this solution should be portable.


I don't know what is the desired behavior for Windows my modified version did work on win-builder but only because there is no cmake installed and it falls back to the Makefile. For cmake to work on Windows you might have to add a `configure.win` file.
Based on [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) the `.exe` file should be then at `${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe`.

In the DESCRIPTION i saw there are two authors, I think you only allowed to name one author with e-mail adress in the DESCRIPTION file.

**Comment by FlorianSchwendinger** [comment]
Also you can easily test if it works for non standard locations.
Install R from source, I always have `~/bin/R<version>` (e.g., `~/bin/R412`) and set R<version> as an alias (e.g., `R412`)
and the following in the `.Rprofile` file.
```{r}
local({
    R_version <- paste(unlist(R.Version()[c("major", "minor")]), collapse = "")
    R_version <- gsub("\\D", "", R_version)
    personal_lib_path <- file.path(Sys.getenv("HOME"), "lib", sprintf("R%s", R_version))
    if ( !file.exists(personal_lib_path) ) {
        dir.create(personal_lib_path)
    }
    .libPaths(personal_lib_path)
})
```
so that I automatically get my own lib Path for each R version installed.

- `osqp_0.6.0.3.tar.gz` is the version currently on CRAN
- `osqp_0.6.0.4.tar.gz` is the pached version

If I then do `R412 CMD INSTALL osqp_0.6.0.3.tar.gz` I get

```
-- We are building the R interface
-- R exec is: /usr/bin/R
-- R root dir is: WARNING: ignoring environment value of R_HOME
/usr/lib/R
-- R includes are in: /usr/share/R/include
```

which is wrong R exec  should be `/home/florian/bin/R_412/bin/R`.
For the patched version (`R412 CMD INSTALL osqp_0.6.0.4.tar.gz`) I get 

```
-- We are building the R interface
-- R exec is: /home/florian/bin/R_412/bin/R
-- R root dir is: /home/florian/bin/R_412
-- R includes are in: /home/florian/bin/R_412/include
```
which is the desired location.
