### ISSUE TITLE
Using OSQP in C with R package as dependency

### ISSUE THREAD

**Issue by david-cortes** [goulart-paul/osqp-r#7]
I would like to use OSQP in a C file that is meant to be wrapped in R and Python (and uploaded to CRAN and PyPI), and I’m wondering what would be the best way of accomplishing this using the OSQP packages in CRAN and PyPI as dependencies.

My first thought was to include all header files from OSQP in the package, generate `osqp_configure.h` and `qdldl_types.h`, and link to the shared object that the CRAN install generates, but the demo example from https://osqp.org/docs/examples/demo.html#c will segfault if I try that.

I realize that for Python it’s possible to directly include the binaries in a wheel, but I think this is not possible for packages that go to CRAN.

Any suggestions on how to create an R package with C code that links to OSQP taking only the CRAN package as dependency? I know it’s possible to create C++ code with Rcpp that would call the R functions (same for Cython in Python), but I’m wondering if there’s a better way.

**Comment by bstellato** [comment]
At the moment we are using Rcpp which is an R standard for interfacing C/C++ code.

You can build a static library that is then linked to your R functions using Rcpp. This is what we do in this package. 

[Here](https://github.com/oxfordcontrol/osqp-r/blob/master/configure) we check if cmake is available and build the library with it. If it is not available, we use the [Makevars](https://github.com/oxfordcontrol/osqp-r/blob/master/src/Makevars) script together with the [Makefile](https://github.com/oxfordcontrol/osqp-r/blob/master/src/osqp/Makefile) script. We designed OSQP to use CMake to make the library creation easier and platform independent but it is not available on CRAN servers. That's why we keep the Makefile option.

Is there any reason why you would not like to use Rcpp?

**Comment by david-cortes** [comment]
> At the moment we are using Rcpp which is an R standard for interfacing C/C++ code.
> 
> You can build a static library that is then linked to your R functions using Rcpp. This is what we do in this package.
> 
> [Here](https://github.com/oxfordcontrol/osqp-r/blob/master/configure) we check if cmake is available and build the library with it. If it is not available, we use the [Makevars](https://github.com/oxfordcontrol/osqp-r/blob/master/src/Makevars) script together with the [Makefile](https://github.com/oxfordcontrol/osqp-r/blob/master/src/osqp/Makefile) script. We designed OSQP to use CMake to make the library creation easier and platform independent but it is not available on CRAN servers. That's why we keep the Makefile option.
> 
> Is there any reason why you would not like to use Rcpp?

It’s not that I wanted to avoid Rcpp, but that I wanted to call the C functions directly (from a C file), rather than use Rcpp to call the R functions which in turn would call the C functions.

**Comment by gbanjac** [comment]
I think this discussion should not be here. For general questions related to OSQP you could use our [forum](https://groups.google.com/forum/#!forum/osqp).
